### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by francescodalbi** [Kinzel/mt5R#2]
Hi, I am trying to install mt5R on my Windows setup but I have this error 
![image](https://user-images.githubusercontent.com/32592051/104087441-0938fd80-5260-11eb-91a3-5c3c94a4a5f9.png)
I already tried to reinstall Rstudio, R and Rtools.

**Comment by Kinzel** [comment]
Thank you! I'll check what happened!

**Comment by francescodalbi** [comment]
Hi, I finally understood what was the problem. Something must have gone wrong at the first download by creating the folder in C:\Users\My_User\Documents\R\win-library\4.0\  anyway... I tried deleting the mt5R folder and was able to download your interesting project! MT5.Ping() responds TRUE so I solved it.
